
folder = [pwd filesep 'TestData' filesep 'Fish 3 - Tumour'];
ometiffilename = [pwd filesep 'TestData' filesep 'Fish 3 - Tumour.OME.tiff'];

if exist(ometiffilename,'file')
    delete(ometiffilename);
end;

addpath_OMEkit;

labels = (0:1:39); 
Tags_SeparatingSeq = 'jkhsadfgleufyihtiwurehfjkiblaherb';
Tags = ['Raw Fish' Tags_SeparatingSeq 'Fried Fish' Tags_SeparatingSeq 'Gefilte Fish'];

save_OPT_stack_as_OMEtiff_with_metadata2(folder, ometiffilename, ...
                    'PhysSz_X', 3.225, ...
                    'PhysSz_Y', 3.225, ...
                    'ModuloZ_Type', 'Rotation', ...
                    'ModuloZ_TypeDescription', 'OPT', ...
                    'ModuloZ_Unit', 'degree', ...
                    'ModuloZ_Start', 0, ...
                    'ModuloZ_Step', 1, ...
                    'ModuloZ_End', 359, ...
                    'Tags', Tags, ...
                    'verbose', true, ...            
                    'Tags_SeparatingSeq', Tags_SeparatingSeq)
%


