               
folder = [pwd filesep 'TestData' filesep 'Fish 3 - Tumour'];
ometiffilename = [pwd filesep 'TestData' filesep 'Fish 3 - Tumour.OME.tiff'];

if exist(ometiffilename,'file')
    delete(ometiffilename)
end;

addpath_OMEkit;
            
physszX = 3.225;
physszY = 3.225;
zdim_label = 'Rotation';
zdim_unit = 'degree';
zdim_typeDescription = 'OPT';
zdim_start = 0;
zdim_end = 359;
zdim_step = 1;

% labels = (0:1:359); 
labels = (0:1:39); 

            extension  = 'tif';
            
            files = dir([folder filesep '*.' extension]);
            num_files = length(files);
            if 0 ~= num_files
                file_names = cell(1,num_files);
                for k = 1:num_files
                    file_names{k} = char(files(k).name);
                end
            else
                return, 
            end;               

            if isempty(file_names) || 0 == numel(file_names), return, end;
             
            acc = zeros(1,num_files);
            for i = 1 : num_files
                                               
                % telapsed = add_plane_to_OMEtiff_with_metadata(I, i, num_files, folder, ometiffilename, ...
                %     'PhysSz_X',physszX, ...
                %     'PhysSz_Y',physszY, ...
                %     'ModuloZ_Type', zdim_label, ...
                %     'ModuloZ_TypeDescription', zdim_typeDescription, ...
                %     'ModuloZ_Unit', zdim_unit, ...
                %     'ModuloZ_Start', zdim_start, ...
                %     'ModuloZ_Step', zdim_step, ...
                %     'ModuloZ_End', zdim_end, ...    
                %     'Tags', 'jlakdsfjmnvlmsfbvlasjfnlsakcnvlsmdnflsakmnvl,samdnvl,mscnv', ...            
                %     'TagsS_eparatingSeq', 'mscnv');
                % 
                telapsed = add_plane_to_OMEtiff_with_metadata(I, i, num_files, folder, ometiffilename, ...
                    'PhysSz_X', physszX, ...
                    'PhysSz_Y', physszY, ...
                    'ModuloZ_Type', zdim_label, ...
                    'ModuloZ_TypeDescription', zdim_typeDescription, ...
                    'ModuloZ_Unit', zdim_unit, ...
                    'ModuloZ_Labels', labels, ...        
                    'Tags', 'jlakdsfjmnvlmsfbvlasjfnlsakcnvlsmdnflsakmnvl,samdnvl,mscnv', ...            
                    'TagsS_eparatingSeq', 'mscnv');

                % telapsed = add_plane_to_OMEtiff_with_metadata(I, i, num_files, folder, ometiffilename, ...
                %     'PhysSz_X',physszX, ...
                %     'PhysSz_Y',physszY, ...
                %     'Tags', 'jlakdsfjmnvlmsfbvlasjfnlsakcnvlsmdnflsakmnvl,samdnvl,mscnv', ...            
                %     'TagsS_eparatingSeq', 'mscnv');

                acc(i)=telapsed;    
                                               
            end
            saveBytes_speed = mean(acc)
                       